name: Deploy to GCE

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
	uses: appleboy/ssh-action@master
	with:
	  host: ${{secrets.GCE_HOST}}
	  username: ${{}}
	  key: ${{}}
	  port: 22
	  script: |
		cd ${{secrets.}}
		git pull origin main
		npm i
		npx prisma generate
		pm2 restart 0
