name: Deploy to GCE

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Pull and restart
        run: |
            cd ${{secrets.GCE_PROJECT_DIR}}
            git pull origin main
            npm i
            npx prisma generate
            tsc
            pm2 restart 0
