name: Deploy to GCE

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.GCE_HOST}}
          username: ${{secrets.GCE_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            cd ${{secrets.GCE_PROJECT_DIR}}
            git pull origin main
            npm i
            npx prisma generate
            tsc
            pm2 restart 0
